name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
      - master
      - feature/auto-deploy-dokku-52

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Cancel Previous Runs # Optional step
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo # This step is required
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This is required, or you might get an error from Dokku

      - name: Push to dokku
        uses: obrassard/action-dokku-deploy@v1.0.3
        with:
          dokku_repo: ${{ secrets.DOKKU_REPO }}
          ssh_key: ${{ secrets.SSH_KEY }}
          deploy_branch: 'develop'
