name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
      - master
      - feature/auto-deploy-dokku-52

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.DOKKU_REPO }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
