name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
      - main
      - feature/auto-deploy-dokku-52

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to dokku
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        dokku-user: 'woutervm_deploy'
        dokku-host: '81.169.175.44'
        app-name: 'woutervm'
        git_push_flags: '--force'
        ssh_private_key: ${{ secrets.SSH_KEY }}
