name: 'Deploy to my Dokku instance'

on:
  push:
    branches:
      - main
      - feature/auto-deploy-dokku-52

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: obrassard/action-dokku-deploy@v1.0.2
        with:
          deploy_branch: 'main'
          git_remote_url: ${{ secrets.DOKKU_REPO }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
